# Model Configuration with LoRA enabled
model:
  path: '/workspace/text-generation-webui/models/Qwen_Qwen2.5-0.5B-Instruct'
  max_seq_length: 256
  dtype: null
  load_in_4bit: false
  # LoRA Configuration - ENABLED
  use_lora: true  # Set to true to enable LoRA training
  lora_config:
    r: 16  # LoRA rank (higher = more parameters, better performance but slower)
    lora_alpha: 32  # LoRA alpha parameter (usually 2*r)
    target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]  # Target modules for LoRA
    lora_dropout: 0.1
    bias: "none"
    task_type: "CAUSAL_LM"

# Dataset Configuration
dataset:
  name: openai/gsm8k
  subset: main
  split: train
  question_column: question  # Name of the question column
  answer_column: answer      # Name of the answer column

# Training Configuration
training:
  epochs: 1
  gradient_accumulation_steps: 1
  per_device_train_batch_size: 1
  warmup_steps: 5
  max_steps: 2000
  learning_rate: 5.0e-5  # Can use higher learning rate with LoRA
  logging_steps: 1
  weight_decay: 0.01
  lr_scheduler_type: linear
  seed: 3407
  output_dir: outputs_lora
  report_to: none
  gen_every_n_steps: 20  # Generate samples every N steps 